import React from "react";

const AllQuestions = {
  css: [
    "What is CSS?",
    "How can you integrate CSS on a web page?",
    "What are the CSS frameworks?",
    "Why background and color are separate properties if they should always be set together?",
    "What is Embedded Style Sheet?",
    "What are the advantages of Embedded Style Sheets?",
    "What is a CSS selector?",
    "What is the use of CSS Opacity?",
    "Explain universal selector.",
    "Which command is used for the selection of all the elements of a paragraph?",
    "Name the property for controlling the image scroll in the background.",
    "What is the use of ruleset?",
    "What is the difference between class selectors and id selectors?",
    "What are the advantages of External Style Sheets?",
    "What is RWD?",
    "What are the benefits of CSS sprites?",
    "What is the CSS Box model and what are its elements?",
    "What is the purpose of the z-index and how is it used?",
    "Explain the difference between visibility: hidden and display: none?",
    "What do you understand by W3C?",
    "What is tweening?",
    "Which type of CSS holds the highest priority?",
    "How can we add comments in CSS?",
    "What does the ‘a’ in rgba mean?",
    "What are CSS HSL Colors?",
    "What are CSS backgrounds, list the properties?",
    "What is the difference between margin and padding?",
    "What is the difference between CSS border and outline?",
    "How can we format text in CSS?",
    "What are the different CSS link states?",
    "How can we hide an element in CSS?",
    "What is the difference between display: none and visibility: hidden?",
    "Can we overlap elements in CSS?",
    "What are the various positioning properties in CSS?",
    "What is CSS overflow?",
    "What does the CSS float property do?",
    "What does display:inline-block do?",
    "What are CSS Combinators?",
    "What are pseudo-classes in CSS?",
    "What are pseudo-elements in CSS?",
    "Can we add 3D transformations to our project using CSS?",
    "What does the CSS box-sizing property do?",
    "How can we make our website responsive using CSS?",
    "What is CSS flexbox?",
    "What is the difference between flexbox and grid?",
    "What is the best way to include a CSS file? Why use @import?",
    "How case-sensitive is CSS?",
    "How can we give a shadow effect to our text in CSS?",
    "What is !important?",
    "What is specificity in CSS?",
  ],
  html: [
    "What is HTML?",
    "What are the various markup languages available?",
    "What is the current version of HTML?",
    "What is !DOCTYPE?",
    "What are elements and tags, and what are the differences between them?",
    "What are the various heading tags and their importance?",
    "How to redirect to a particular section of a page using HTML?",
    "What are attributes?",
    "Are <b> and <strong> tags same? If not, then why?",
    "What is the difference between <em> and <i> tags?",
    " How are comments added in HTML?",
    "What is the use of alt attribute in images?",
    "What are the HTML tags used to display a table?",
    "What are the different types of lists in HTML?",
    "What is the difference between block and inline elements?",
    "Are <div> and <span> tags similar?",
    "How can we create a nested webpage in HTML?",
    "What are the tags that can be used inside the <head> tag?",
    "What are meta tags? How are they important?",
    "What are semantic elements?",
    "How can we add symbols in HTML?",
    "What is the difference between the POST method and the GET method?",
    "What is HTML Canvas?",
    "What is SVG?",
    "What is HTML Web Storage API?",
    "What are forms in HTML?",
    "What are void elements?",
    "How to change an inline element into a block-level element?",
    "What tags are used to separate a section of text?",
    "How to create scrolling text or images on a webpage?",
    "What do you mean by manifest file in HTML5?",
    "How to open a hyperlink in another window or tab in HTML?",
    "Explain Web Worker in HTML.",
    "What are Tags?",
    "How many types of heading does an HTML contain?",
    "How to create a hyperlink in HTML?",
    " How to create a nested webpage in HTML?",
    "Explain the layout of HTML?",
    "What is a marquee?",
    "Does a <!DOCTYPE html> tag is a HTML tag?",
  ],
};

export default AllQuestions;
